In [17]:
import pandas as pd
import numpy as np

In [18]:
#import du CSV ligue1

ligue_1 = pd.read_csv('Ligue1.csv', encoding='ISO-8859-1')
ligue_1.head()

,Unnamed: 0,Player,Nation,Pos,Age,Playing Time,Playing Time.1,Playing Time.2,Performance,Performance.1,...,Per 90 Minutes.2,Per 90 Minutes.3,Per 90 Minutes.4,Per 90 Minutes.5,Per 90 Minutes.6,Per 90 Minutes.7,Per 90 Minutes.8,Per 90 Minutes.9,Unnamed: 33,-additional
0,Player,Nation,Pos,Age,MP,Starts,Min,90s,Gls,Ast,...,G+A,G-PK,G+A-PK,xG,xAG,xG+xAG,npxG,npxG+xAG,Matches,-9999
1,Brice Samba,fr FRA,GK,29-018,35,35,3150,35.0,0,0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Matches,60d90c55
2,Kevin Danso,at AUT,DF,24-236,35,35,3078,34.2,1,2,...,0.09,0.03,0.09,0.07,0.03,0.10,0.07,0.10,Matches,6e33125f
3,Seko Fofana,ci CIV,MF,28-006,33,32,2893,32.1,6,4,...,0.31,0.16,0.28,0.26,0.11,0.36,0.21,0.31,Matches,5313ed43
4,Florian Sotoca,fr FRA,MFFW,32-200,35,32,2858,31.8,6,8,...,0.44,0.16,0.41,0.32,0.25,0.57,0.25,0.50,Matches,7a42d0df

In [19]:
#Selection des colonnes que l'on souhaite garder

ligue_1 = ligue_1.loc[:, ['Unnamed: 0', 'Player', 'Nation', 'Pos']]
ligue_1.head()

       Unnamed: 0  Player Nation     Pos
0          Player  Nation    Pos     Age
1     Brice Samba  fr FRA     GK  29-018
2     Kevin Danso  at AUT     DF  24-236
3     Seko Fofana  ci CIV     MF  28-006
4  Florian Sotoca  fr FRA   MFFW  32-200

In [20]:
#renommage des colonnes

ligue_1.columns = ['Player', 'Nation', 'Pos', 'Age']
ligue_1.head()

           Player  Nation   Pos     Age
0          Player  Nation   Pos     Age
1     Brice Samba  fr FRA    GK  29-018
2     Kevin Danso  at AUT    DF  24-236
3     Seko Fofana  ci CIV    MF  28-006
4  Florian Sotoca  fr FRA  MFFW  32-200

In [21]:
#Supprimer la premiÃ¨re ligne

ligue_1 = ligue_1.drop(0)
ligue_1.head()

              Player  Nation   Pos     Age
1        Brice Samba  fr FRA    GK  29-018
2        Kevin Danso  at AUT    DF  24-236
3        Seko Fofana  ci CIV    MF  28-006
4     Florian Sotoca  fr FRA  MFFW  32-200
5  Salis Abdul Samed  gh GHA    MF  23-048

In [22]:
#traitement colonne Nation

ligue_1['Nation'] = ligue_1['Nation'].str.replace('[a-z]', '', regex=True)
ligue_1

                Player Nation   Pos     Age
1          Brice Samba    FRA    GK  29-018
2          Kevin Danso    AUT    DF  24-236
3          Seko Fofana    CIV    MF  28-006
4       Florian Sotoca    FRA  MFFW  32-200
5    Salis Abdul Samed    GHA    MF  23-048
..                 ...    ...   ...     ...
668    Yassin Belkhdim    FRA    MF  21-088
669         ThÃ©o Borne    FRA    GK  20-302
670        Yacine Gaya    ALG    DF  18-179
671   Noah Guede-Nadje    FRA    MF  19-182
672      Demba N'Diaye    FRA    MF  17-268

[672 rows x 4 columns]

In [23]:
ligue_1['Nation'] = ligue_1['Nation'].str.strip()

In [24]:
#remplacement des codes pays

pays ={"AFG": "Afghanistan",
    "ALB": "Albanie",
    "ALG": "AlgÃ©rie",
    "AND": "Andorre",
    "ANG": "Angola",
    "ANT": "Antigua-et-Barbuda",
    "ARG": "Argentine",
    "ARM": "ArmÃ©nie",
    "ARU": "Aruba",
    "ASA": "Samoa amÃ©ricaines",
    "AUS": "Australie",
    "AUT": "Autriche",
    "AZE": "AzerbaÃ¯djan",
    "BAH": "Bahamas",
    "BAN": "Bangladesh",
    "BAR": "Barbade",
    "BDI": "Burundi",
    "BEL": "Belgique",
    "BEN": "BÃ©nin",
    "BER": "Bermudes",
    "BFA": "Burkina Faso",
    "BHU": "Bhoutan",
    "BIH": "Bosnie-HerzÃ©govine",
    "BIZ": "Belize",
    "BLR": "BiÃ©lorussie",
    "BOL": "Bolivie",
    "BOT": "Botswana",
    "BRA": "BrÃ©sil",
    "BRN": "BahreÃ¯n",
    "BRU": "Brunei",
    "BUL": "Bulgarie",
    "BUR": "Burkina Faso",
    "CAF": "RÃ©publique centrafricaine",
    "CAM": "Cambodge",
    "CAN": "Canada",
    "CAY": "ÃŽles CaÃ¯mans  ÃŽles CaÃ¯mans",
    "CGO": "RÃ©publique du Congo",
    "CHA": "Tchad",
    "CHI": "Chili",
    "CHN": "Chine, RÃ©publique populaire de",
    "CIV": "CÃ´te d'Ivoire",
    "CMR": "Cameroun",
    "COD": "RÃ©publique dÃ©mocratique du Congo",
    "COK": "ÃŽles Cook",
    "COL": "Colombie",
    "COM": "Comores",
    "COR": "CorÃ©e unifiÃ©e",
    "CPV": "Cap-Vert",
    "CRC": "Costa Rica",
    "CRO": "Croatie",
    "CUB": "Cuba",
    "CYP": "Chypre",
    "RTCN": "Chypre du Nord",
    "CZE": "TchÃ©quie",
    "DEN": "Danemark",
    "DJI": "Djibouti",
    "DMA": "Dominique",
    "DOM": "RÃ©publique dominicaine",
    "ECU": "Ã‰quateur",
    "EGY": "Ã‰gypte",
    "ENG": "Angleterre",
    "ERI": "Ã‰rythrÃ©e",
    "ESA": "Salvador",
    "ESP": "Espagne",
    "EST": "Estonie",
    "ETH": "Ã‰thiopie",
    "FIJ": "Fidji",
    "FIN": "Finlande",
    "FRA": "France",
    "FSM": "Ã‰tats fÃ©dÃ©rÃ©s de MicronÃ©sie",
    "GAB": "Gabon",
    "GAM": "Gambie",
    "GBR": "Grande-Bretagne",
    "GBS": "GuinÃ©e-Bissau",
    "GEO": "GÃ©orgie",
    "GEQ": "GuinÃ©e Ã©quatoriale",
    "GER": "Allemagne",
    "GHA": "Ghana",
    "GLP": "France",
    "GNB": "Gabon",
    "GRE": "GrÃ¨ce",
    "GRN": "Grenade",
    "GUA": "Guatemala",
    "GUF": "France",
    "GUI": "GuinÃ©e",
    "GUM": "Guam",
    "GUY": "Guyana",
    "HAI": "HaÃ¯ti",
    "HKG": "Hong Kong",
    "HON": "Honduras",
    "HUN": "Hongrie",
    "INA": "IndonÃ©sie",
    "IND": "Inde",
    "IRI": "Iran  Iran",
    "IRL": "Irlande",
    "IRQ": "Irak",
    "ISL": "Islande",
    "ISR": "IsraÃ«l",
    "ISV": "ÃŽles Vierges des Ã‰tats-Unis",
    "ITA": "Italie",
    "IVB": "ÃŽles Vierges britanniques",
    "JAM": "JamaÃ¯que",
    "JOR": "Jordanie",
    "JPN": "Japon",
    "KAZ": "Kazakhstan",
    "KEN": "Kenya",
    "KGZ": "Kirghizistan",
    "KIR": "Kiribati",
    "KOS": "Kosovo",
    "KOR": "CorÃ©e du Sud",
    "KSA": "Arabie saoudite",
    "KUW": "KoweÃ¯t",
    "KVX": "Kosovo",
    "LAO": "Laos",
    "LAT": "Lettonie",
    "LBA": "Libye",
    "LBN": "Liban",
    "LBR": "Liberia",
    "LCA": "Sainte-Lucie",
    "LES": "Lesotho",
    "LIE": "Liechtenstein",
    "LTU": "Lituanie",
    "LUX": "Luxembourg",
    "MAD": "Madagascar",
    "MAR": "Maroc",
    "MAS": "Malaisie",
    "MAW": "Malawi",
    "MDA": "Moldavie",
    "MDV": "Maldives",
    "MEX": "Mexique",
    "MGL": "Mongolie",
    "MHL": "ÃŽles Marshall",
    "MKD": "MacÃ©doine du Nord",
    "MLI": "Mali",
    "MLT": "Malte",
    "MNE": "MontÃ©nÃ©gro",
    "MON": "Monaco",
    "MOZ": "Mozambique",
    "MRI": "Maurice",
    "MTN": "Mauritanie",
    "MTQ": "Martinique",
    "MYA": "Birmanie",
    "NAM": "Namibie",
    "NCA": "Nicaragua",
    "NED": "Pays-Bas",
    "NEP": "NÃ©pal",
    "NGA": "Nigeria",
    "NGR": "Nigeria",
    "NIG": "Niger",
    "NOR": "NorvÃ¨ge",
    "NRU": "Nauru",
    "NZL": "Nouvelle-ZÃ©lande",
    "OAR": "AthlÃ¨tes olympiques de Russie",
    "OMA": "Oman",
    "PAK": "Pakistan",
    "PAN": "Panama",
    "PAR": "Paraguay",
    "PER": "PÃ©rou",
    "PHI": "Philippines",
    "PLE": "Palestine",
    "PLW": "Palaos",
    "PNG": "Papouasie-Nouvelle-GuinÃ©e",
    "POL": "Pologne",
    "POR": "Portugal",
    "PRK": "CorÃ©e du Nord",
    "PUR": "Porto Rico",
    "QAT": "Qatar",
    "ROC": "ComitÃ© olympique de Russie",
    "ROT": "Ã‰quipe olympique des rÃ©fugiÃ©s",
    "ROU": "Roumanie",
    "RSA": "Afrique du Sud",
    "RUS": "Russie, FÃ©dÃ©ration de",
    "RWA": "Rwanda",
    "SAM": "Samoa",
    "SCO": "Ã‰cosse",
    "SEN": "SÃ©nÃ©gal",
    "SEY": "Seychelles",
    "SGP": "Singapour",
    "SKN": "Saint-Christophe-et-NiÃ©vÃ¨s",
    "SLE": "Sierra Leone",
    "SLO": "SlovÃ©nie",
    "SMR": "Saint-Marin",
    "SOL": "ÃŽles Salomon",
    "SOM": "Somalie",
    "SRB": "Serbie",
    "SRI": "Sri Lanka",
    "SSD": "Soudan du Sud",
    "STP": "Sao TomÃ©-et-Principe",
    "SUD": "Soudan",
    "SUI": "Suisse",
    "SUR": "Suriname",
    "SVK": "Slovaquie",
    "SVN": "SlovÃ©nie",
    "SWE": "SuÃ¨de",
    "SWZ": "Eswatini/Swaziland",
    "SYR": "Syrie",
    "TAN": "Tanzanie, RÃ©publique unie de",
    "TGA": "Tonga",
    "THA": "ThaÃ¯lande",
    "TJK": "Tadjikistan",
    "TKM": "TurkmÃ©nistan",
    "TLS": "Timor oriental",
    "TOG": "Togo",
    "TPE": "Taipei chinois",
    "TTO": "TrinitÃ©-et-Tobago",
    "TUN": "Tunisie  Tunisie",
    "TUR": "Turquie",
    "TUV": "Tuvalu",
    "UAE": "Ã‰mirats arabes unis",
    "UGA": "Ouganda",
    "UKR": "Ukraine",
    "URU": "Uruguay",
    "USA": "Ã‰tats-Unis",
    "UZB": "OuzbÃ©kistan",
    "VAN": "Vanuatu",
    "VEN": "Venezuela",
    "VIE": "ViÃªt Nam",
    "VIN": "Saint-Vincent-et-les-Grenadines",
    "WAL": "Pays de Galles",
    "YEM": "YÃ©men",
    "ZAM": "Zambie  Zambie",
    "ZIM": "Zimbabwe"
}

ligue_1['Nation'] = ligue_1['Nation'].map(pays)
ligue_1

                Player         Nation   Pos     Age
1          Brice Samba         France    GK  29-018
2          Kevin Danso       Autriche    DF  24-236
3          Seko Fofana  CÃ´te d'Ivoire    MF  28-006
4       Florian Sotoca         France  MFFW  32-200
5    Salis Abdul Samed          Ghana    MF  23-048
..                 ...            ...   ...     ...
668    Yassin Belkhdim         France    MF  21-088
669         ThÃ©o Borne         France    GK  20-302
670        Yacine Gaya        AlgÃ©rie    DF  18-179
671   Noah Guede-Nadje         France    MF  19-182
672      Demba N'Diaye         France    MF  17-268

[672 rows x 4 columns]

In [25]:
#traitement colonne age

ligue_1['Age'] = ligue_1['Age'].str.slice(stop=2)
ligue_1.head()

              Player         Nation   Pos Age
1        Brice Samba         France    GK  29
2        Kevin Danso       Autriche    DF  24
3        Seko Fofana  CÃ´te d'Ivoire    MF  28
4     Florian Sotoca         France  MFFW  32
5  Salis Abdul Samed          Ghana    MF  23

In [26]:
#Changement des postes

position = {"GK":"Gardien",
            "DF":"DÃ©fenseur",
            "FWMF":"Milieu Offensif",
            "FW":"Attaquant",
            "MF":"Milieu DÃ©fensif",
            "DFMF":"LatÃ©ral",
            "MFFW":"Milieu Offensif",
            "MFDF":"Milieu DÃ©fensif"}

ligue_1['Pos'] = ligue_1['Pos'].map(position)
ligue_1

                Player         Nation              Pos Age
1          Brice Samba         France          Gardien  29
2          Kevin Danso       Autriche        DÃ©fenseur  24
3          Seko Fofana  CÃ´te d'Ivoire  Milieu DÃ©fensif  28
4       Florian Sotoca         France  Milieu Offensif  32
5    Salis Abdul Samed          Ghana  Milieu DÃ©fensif  23
..                 ...            ...              ...  ..
668    Yassin Belkhdim         France  Milieu DÃ©fensif  21
669         ThÃ©o Borne         France          Gardien  20
670        Yacine Gaya        AlgÃ©rie        DÃ©fenseur  18
671   Noah Guede-Nadje         France  Milieu DÃ©fensif  19
672      Demba N'Diaye         France  Milieu DÃ©fensif  17

[672 rows x 4 columns]

In [27]:
#import de psg dans python

psg = pd.read_csv('psg_clean.csv')
psg.head()

   Unnamed: 0                Player     Nation              Pos  Age
0           1  Gianluigi Donnarumma     Italie          Gardien   24
1           2            Marquinhos     BrÃ©sil        DÃ©fenseur   28
2           3          Lionel Messi  Argentine  Milieu Offensif   35
3           4         Kylian MbappÃ©     France        Attaquant   24
4           5          Sergio Ramos    Espagne        DÃ©fenseur   37

In [28]:
psg = psg.drop('Unnamed: 0', axis= 1)
psg

                    Player      Nation              Pos  Age
0     Gianluigi Donnarumma      Italie          Gardien   24
1               Marquinhos      BrÃ©sil        DÃ©fenseur   28
2             Lionel Messi   Argentine  Milieu Offensif   35
3            Kylian MbappÃ©      France        Attaquant   24
4             Sergio Ramos     Espagne        DÃ©fenseur   37
5                  Vitinha    Portugal  Milieu DÃ©fensif   23
6           Danilo Pereira    Portugal          LatÃ©ral   31
7           Marco Verratti      Italie  Milieu DÃ©fensif   30
8            Achraf Hakimi       Maroc          LatÃ©ral   24
9         FabiÃ¡n Ruiz PeÃ±a     Espagne  Milieu DÃ©fensif   27
10             Nuno Mendes    Portugal        DÃ©fenseur   20
11                  Neymar      BrÃ©sil  Milieu Offensif   31
12             Juan Bernat     Espagne        DÃ©fenseur   30
13            Carlos Soler     Espagne  Milieu DÃ©fensif   26
14           Nordi Mukiele      France        DÃ©fenseur   25
15            Hugo Ekitike      France        Attaquant   20
16        Presnel Kimpembe      France        DÃ©fenseur   27
17      Warren Zaire-Emery      France  Milieu DÃ©fensif   17
18          Renato Sanches    Portugal  Milieu DÃ©fensif   25
19  El Chadaille Bitshiabu      France        DÃ©fenseur   17
20        Timothee Pembele      France        DÃ©fenseur   20
21           Pablo Sarabia     Espagne  Milieu Offensif   31
22           IsmaÃ«l Gharbi     Espagne  Milieu Offensif   19
23         Leandro Paredes   Argentine  Milieu DÃ©fensif   28
24            Ilyes Housni      France        Attaquant   17
25            Abdou Diallo     SÃ©nÃ©gal        DÃ©fenseur   27
26      Nehemiah Fernandez      France        DÃ©fenseur   18
27       Arnaud Kalimuendo      France        Attaquant   21
28              Ayman Kari      France  Milieu DÃ©fensif   18
29               Hugo Lamy      France        DÃ©fenseur   19
30     Alexandre Letellier      France          Gardien   32
31            Keylor Navas  Costa Rica          Gardien   36
32             Serif Nhaga    Portugal        DÃ©fenseur   17
33             Sergio Rico     Espagne          Gardien   29

In [29]:
ligue_1_clean = pd.concat([ligue_1, psg], ignore_index=True)

ligue_1_clean

                  Player         Nation              Pos Age
0            Brice Samba         France          Gardien  29
1            Kevin Danso       Autriche        DÃ©fenseur  24
2            Seko Fofana  CÃ´te d'Ivoire  Milieu DÃ©fensif  28
3         Florian Sotoca         France  Milieu Offensif  32
4      Salis Abdul Samed          Ghana  Milieu DÃ©fensif  23
..                   ...            ...              ...  ..
701            Hugo Lamy         France        DÃ©fenseur  19
702  Alexandre Letellier         France          Gardien  32
703         Keylor Navas     Costa Rica          Gardien  36
704          Serif Nhaga       Portugal        DÃ©fenseur  17
705          Sergio Rico        Espagne          Gardien  29

[706 rows x 4 columns]

In [30]:
#ligue_1_clean.to_csv('Ligue1_Clean.csv')

In [31]:
#vÃ©rification des NaNs

ligue_1_clean.isnull().sum()

Player     0
Nation     7
Pos       19
Age        0
dtype: int64

In [32]:
#afficher uniquement les lignes contenant des nans.

df_nan = ligue_1_clean[ligue_1_clean.isnull().any(axis=1)]

df_nan

                  Player              Nation              Pos Age
21       IsmaÃ«lben Boura              France              NaN  22
111         Timothy Weah          Ã‰tats-Unis              NaN  23
113        Edon Zhegrova              Kosovo              NaN  24
115  Gabriel Gudmundsson               SuÃ¨de              NaN  24
189             Henrique              BrÃ©sil              NaN  29
225        Ayoub Amraoui               Maroc              NaN  18
260        Darlin Yongwa            Cameroun              NaN  22
287         Alexis Flips              France              NaN  23
299  Mitchell van Bergen            Pays-Bas              NaN  23
309        Mohamed Toure           Australie              NaN  19
322        Jim Allevinah               Gabon              NaN  28
358     Faitout Maouassa              France              NaN  24
374       Arnaud Souquet              France              NaN  31
472   Christophe HÃ©relle                 NaN        DÃ©fenseur  30
483     Karamoko Dembele                 NaN  Milieu Offensif  20
512         Donovan LÃ©on                 NaN          Gardien  30
522       ThÃ©o De Percin                 NaN          Gardien  22
545          Marcus Coco              France              NaN  26
597        Yoann Salmier                 NaN        DÃ©fenseur  30
598     Mama Samba BaldÃ©                 NaN        Attaquant  27
606        Andreas Bruus            Danemark              NaN  24
639    Souleyman Doumbia       CÃ´te d'Ivoire              NaN  26
641          Miha BlaÂži?                 NaN        DÃ©fenseur  30
648      Farid El Melali             AlgÃ©rie              NaN  26
651          Sada Thioub             SÃ©nÃ©gal              NaN  27
656      Halid ÂŠabanovi?  Bosnie-HerzÃ©govine              NaN  23